### 1. What is a Python library? Why do we use Python libraries?

In [ ]:
Python library is a collection of a code that we can use in a program for specific operations.
Using a Python library is convenient to include reused code into your projects and programs.

### 2. What is the difference between Numpy array and List?

In [ ]:
The Difference between Numpy and List is:-
Numpy is the python library to store the collection of code to perform a specific operation. Numpy is type of array
List is datatype to store a multiple data. list contain any type of data.

### 3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [1]:
import numpy as np

In [13]:
arr = np.asanyarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr.shape


(3, 4)

In [15]:
arr.ndim

2

In [16]:
arr.size

12

### 4. Write python code to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
# 2d array make
arr = np.asanyarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
# first row of the following array
arr[0]

array([1, 2, 3, 4])

### 5. How do you access the element at the thir^ row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [12]:
# 2d array make
arr = np.asanyarray([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr
# print Third row  of the  array
arr[2 ,3]


12

### 6. Write co^e to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [2]:
import numpy as np

# Define the array
arr= np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

# Print the result
print("Odd-indexed elements:", odd_indexed_elements)


Odd-indexed elements: [[ 2  4]
 [ 6  8]
 [10 12]]


### 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [11]:
# import numpy and random
import random
import numpy as np
# print  3 x 3 matrix
np.random.rand(3,3)

array([[0.76245713, 0.17453651, 0.54608895],
       [0.75383783, 0.21478736, 0.67275702],
       [0.83639241, 0.95447656, 0.99365568]])

### 8. Describe the difference between np.random.rand and np.random.randn?

In [12]:
np.random.rand
The np.random.rand function generates random values from a uniform distribution over the half-open interval [0.0, 1.0)
                                                                                                             
np.random.randn
The np.random.randn function generates random values from a standard normal distribution (mean=0, standard deviation=1).                                                                                                           

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (4120070109.py, line 2)

### 9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [13]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase dimension by adding a new axis
new_dimension_array = original_array[:, :, np.newaxis]

# Print the original and new arrays
print("Original array:")
print(original_array)

print("\nArray with increased dimension:")
print(new_dimension_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimension:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


### 10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [17]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
transposed_array = np.transpose(original_array)

# Print the original and transposed arrays
print("Original array:")
print(original_array)

print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### 11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [29]:
import numpy as np
# given array
matrixA2 =np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrixB2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# print the result
print("matrixA2:")
print(matrixA2)

print("\nmatrixB2:")
print(matrixB2)

print("Add is: " ,matrixA2 + matrixB2)
print("Substract: " ,matrixB2 - matrixA2)
#print("multiplication: ", matrixA2 @  matrixB2)
print("Divide is: " , matrixB2 / matrixA2)


matrixA2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

matrixB2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Add is:  [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Substract:  [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Divide is:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

In [30]:
import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order of the array
swapped_array = original_array.byteswap()

# Print the original and swapped arrays
print("Original array:")
print(original_array)

print("\nSwapped array:")
print(swapped_array)


Original array:
[1 2 3 4]

Swapped array:
[16777216 33554432 50331648 67108864]


### 15. What is broadcasting in Numpy?

In [32]:
# The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations


# example
import numpy as np

# Create a 2x3 array
A = np.array([[1, 2, 3], [4, 5, 6]])

# Add a scalar (5) to each element in the array using broadcasting
result = A + 5

# Print the result
print(result)


[[ 6  7  8]
 [ 9 10 11]]


### 14. What does the np.reshape function do, and how is it used?

In [35]:
import numpy as np

# Example 1: Reshaping a 1D array to a 2D array
arr1= np.array([1, 2, 3, 4, 5, 6])
arr2 = np.reshape(arr1, (2, 3))
# display the result
print(arr2)

[[1 2 3]
 [4 5 6]]


### 13.  What is the significance of the np.linalg.inv function?